
GET http://localhost:3000/api/users/me
Authorization: Bearer TOKEN

# PATCH http://localhost:3000/api/users/me 
# Content-Type: application/json
# Authorization: Bearer TOKEN

# {
#     "username" : "CHANGED",
#     "email": "EMAIL@mail.com"
# }

# PATCH http://localhost:3000/api/users/changepass
# Content-Type: application/json
# Authorization: Bearer TOKEN

# {
#     "oldPassword": "passwordlong",
#     "newPass": "NEWLONGPASSWORD",
#     "newPassConfirm" : "NEWLONGPASSWORD"
# }

# DELETE http://localhost:3000/api/users/me
# Authorization: Bearer 
